import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { getPaginationData } from 'helpers/pagination';
import { BASIC_FIELDS, getAllPosts, Post } from 'lib/post';
import styles from 'styles/Home.module.css';

export const homeDataTestIds = {
  heading: 'home-heading',
};

interface HomeProps {
  posts: Post[];
}

const Home = ({ posts }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} data-test-id={homeDataTestIds.heading}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {posts.map((post) => (
            <Link href="/posts/[id]" as={`/posts/${post.slug}`} key={post.slug}>
              <a href={`/posts/${post.slug}`} className={styles.card}>
                <h2>{post.title}</h2>
                <Image
                  src={post.coverImage}
                  alt={post.title}
                  width={480}
                  height={320}
                  layout="responsive"
                  objectFit="contain"
                />
                <p>{post.excerpt}</p>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const posts = getAllPosts(BASIC_FIELDS);
  const { paginatedItems } = getPaginationData(posts, 1);

  return {
    props: { posts: paginatedItems },
  };
};
