name: Test

on: push

env:
  NEXT_PUBLIC_BASE_PATH: /til

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm run test -- --coverage --watchAll=false --ci

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: coverage/coverage-final.json

  ui-test:
    name: UI test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build application
        run: npm run build

      - name: Run UI test
        uses: cypress-io/github-action@v2
        with:
          start: npm run start -- -p 3003
          wait-on: http://localhost:3003/til
          browser: chrome
          headless: true

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
